[package]
name = "atlas"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
futures-util = "0.3.31"
log = "0.4.26"
quinn = "0.11.6"
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.2"
